version: "3"

services:
  database:
    image: mysql
    container_name: skkuchin-db
    environment:
      - MYSQL_DATABASE=service
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    ports:
      - 3306:3306
    # db 데이터 유지하고 싶을 때 밑의 2줄 주석 풀기 
    # volumes:
    #   - ./db/data:/var/lib/mysql
    networks:
      - skkuchin-network

  server:
    image: server
    build:
      context: "./backend"
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8080:8080
    # volumes:
    #   - ./backend:/app
    # working_dir: /app
    depends_on:
      - database
    container_name: skkuchin-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - RABBITMQ_HOST=rabbitmq
    networks:
      - skkuchin-network

  client:
    image: client
    build:
      context: "./frontend"
      dockerfile: Dockerfile.dev
    restart: always
    container_name: skkuchin-frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_KAKAOMAP_APPKEY=53a909c464c1aac1af1ee43c1f03ce86
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    stdin_open: true
    tty: true
    networks:
      - skkuchin-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15670:15670"
      - "15672:15672"
      - "61613:61613"
    command: sh -c "rabbitmq-plugins enable rabbitmq_web_stomp rabbitmq_web_stomp_examples && rabbitmq-server start"
    networks:
      - skkuchin-network

networks:
  skkuchin-network: